const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
const source=fs.readFileSync(require('node:path').join(__dirname,'../server/google-mail/Code.gs'),'utf8');
function harness(options={}){const props={},sent=[];const context={ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},LockService:{getScriptLock:()=>({tryLock:()=>!options.busy,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>{props[k]=v;}})},MailApp:{getRemainingDailyQuota:()=>options.quota??100,sendEmail:mail=>{if(options.fail)throw Error();sent.push(mail);}},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>crypto.createHash('sha256').update(s).digest(),base64EncodeWebSafe:b=>b.toString('base64url')}};vm.createContext(context);vm.runInContext(source,context);return {context,sent,props,send:data=>context.doPost({postData:{contents:JSON.stringify(data)}})};}
const input=()=>({name:'Test locale',email:'fixture@example.com',message:'Richiesta di prova locale, nessun invio reale.',requestId:crypto.randomUUID(),privacyAcknowledged:true,website:''});
test('Destinazione fissa, Reply-To verificato, idempotenza',()=>{const h=harness(),data={...input(),to:'attacker@example.com'};assert.equal(h.send(data).ok,true);assert.equal(h.sent[0].to,'zulian.architettura.digitale@gmail.com');assert.equal(h.sent[0].replyTo,data.email);assert.equal(h.send(data).ok,true);assert.equal(h.sent.length,1);});
test('Rifiuta dati incompleti, injection, honeypot e mancata presa visione',()=>{for(const bad of [{name:'x'},{email:'a@example.com\nBcc:bad@example.com'},{message:'short'},{privacyAcknowledged:false},{website:'spam'},{requestId:'not-uuid'}]){const h=harness();assert.equal(h.send({...input(),...bad}).ok,false);assert.equal(h.sent.length,0);}});
test('Limite tre richieste per mittente/ora',()=>{const h=harness();for(let i=0;i<3;i++)assert.equal(h.send(input()).ok,true);assert.equal(h.send(input()).code,'rate');assert.equal(h.sent.length,3);});
test('Quota e concorrenza non producono false conferme',()=>{for(const opts of [{quota:0},{busy:true}]){const h=harness(opts);assert.equal(h.send(input()).ok,false);assert.equal(h.sent.length,0);}});
test('Errore provider rimane incerto; retry non duplica',()=>{const h=harness({fail:true}),data=input();assert.equal(h.send(data).code,'uncertain');assert.equal(h.send(data).code,'uncertain');assert.equal(h.sent.length,0);});
test('Non conserva testo, nome o email nel registro tecnico',()=>{const h=harness();h.send(input());const text=JSON.stringify(h.props);for(const s of ['fixture@example.com','Test locale','nessun invio reale'])assert.equal(text.includes(s),false);});
