from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parent.parent;OUT=ROOT/'public';e=html.escape
tiers=[('essential',1100,'Presenza chiara', ['','servizi','contatti']),('business',1600,'Scelta accompagnata',['','servizi','metodo','domande','contatti']),('signature',2400,'Percorsi e profondità',['','servizi','impianti','manutenzione','metodo','guida','documentazione','contatti'])]
names={'':'Home','servizi':'Servizi','contatti':'Richiesta','metodo':'Metodo','domande':'Domande','impianti':'Impianti','manutenzione':'Manutenzione','guida':'Guida','documentazione':'Documentazione'}
for tier,price,concept,routes in tiers:
 base=f'/demo/elettricisti-{tier}/';folder=OUT/base.strip('/');folder.mkdir(parents=True,exist_ok=True)
 for route in routes:
  nav=''.join(f'<a href="{base}{r+"/" if r else ""}" '+('aria-current="page" ' if r==route else '')+f'>{names[r]}</a>' for r in routes)
  head=f'<div class="demo-bar"><a href="/modelli/">← Catalogo Zulian</a><span>DEMO · {tier.upper()} · {len(routes)} pagine · €{format(price,',').replace(',','.')} IVA inclusa</span><a href="/advisor/?model=electric-{tier}&amp;package={tier}">Valuta questo livello ↗</a></div><header><a href="{base}" class="demo-brand">MODELLO<br><b>ELETTRICISTI</b></a><nav aria-label="Navigazione demo">{nav}</nav><button class="demo-menu" aria-expanded="false" aria-controls="demo-mobile">Menu +</button></header><nav class="demo-mobile" id="demo-mobile" aria-label="Menu mobile" hidden>{nav}</nav>'
  art='<svg class="circuit" viewBox="0 0 600 600" aria-hidden="true"><defs><pattern id="d" width="30" height="30" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".28"/></pattern></defs><rect width="600" height="600" fill="url(#d)"/><g fill="none" stroke="currentColor"><rect x="110" y="110" width="340" height="340" stroke-width="1"/><path d="M60 300H210V180H390V420H210V300H540M300 60V110M300 450V540" stroke-width="2"/><circle cx="300" cy="300" r="65"/><circle cx="300" cy="300" r="120" opacity=".3"/><path d="M315 250L280 307H320L288 351" stroke-width="8"/><circle cx="60" cy="300" r="8"/><circle cx="540" cy="300" r="8"/></g></svg>'
  prefix='<p class="label">CONTENUTI ESEMPLIFICATIVI · NESSUNA IMPRESA REALE RAPPRESENTATA</p>'
  if not route:
   title={'essential':'Il tuo impianto.<br>Una richiesta chiara.','business':'Capire il problema.<br>Preparare l’intervento.','signature':'Ogni impianto<br>ha un percorso.'}[tier]
   body=f'<section class="demo-hero"><div>{prefix}<span class="label">{concept} / {tier}</span><h1>{title}</h1><p>Un esempio di sito per servizi elettrici: informazioni organizzate per aiutare una persona a descrivere ciò che le serve.</p><div class="demo-actions"><a class="demo-btn" href="{base}servizi/">Esplora i servizi →</a><a href="{base}contatti/">Prova la richiesta</a></div></div><div class="demo-art">{art}</div></section><section class="demo-section"><span class="label">COME FUNZIONA QUESTO MODELLO</span><h2>Dall’informazione<br>alla richiesta.</h2><div class="demo-columns"><article><span>01</span><h3>Individua il bisogno.</h3><p>Servizi descritti per contesto, senza promesse tecniche non verificate.</p></article><article><span>02</span><h3>Prepara le informazioni.</h3><p>Tipo di spazio, situazione e obiettivo aiutano a impostare il contatto.</p></article><article><span>03</span><h3>Richiedi una valutazione.</h3><p>Il modulo è una simulazione esplicita. Non invia dati né prenota interventi.</p></article></div></section>'
   if tier=='signature':body+=f'<section class="demo-section tone"><span class="label">SCEGLI IL PERCORSO</span><h2>Da quale situazione parti?</h2><div class="demo-choices"><a href="{base}impianti/">Nuovo impianto o rifacimento ↗</a><a href="{base}manutenzione/">Manutenzione o problema da descrivere ↗</a></div></section>'
  elif route=='servizi':
   body=f'<section class="demo-page">{prefix}<h1>Il servizio giusto<br>parte dal contesto.</h1><p>Questi sono esempi editoriali di organizzazione dei servizi. Ambiti, disponibilità e abilitazioni vanno sostituiti con dati verificati dell’impresa.</p></section><section class="demo-section"><div class="service-row"><span>01</span><div><h2>Impianti e rifacimenti</h2><p>Organizza una richiesta descrivendo spazio, situazione attuale e obiettivo. La fattibilità si definisce con il professionista.</p></div><a href="{base}{"impianti" if tier=="signature" else "contatti"}/">Approfondisci ↗</a></div><div class="service-row"><span>02</span><div><h2>Manutenzione</h2><p>Descrivi il problema osservato senza effettuare prove o manovre rischiose. Il sito non fornisce diagnosi o istruzioni operative.</p></div><a href="{base}{"manutenzione" if tier=="signature" else "contatti"}/">Prepara la richiesta ↗</a></div></section>'
  elif route=='metodo':
   body=f'<section class="demo-page">{prefix}<h1>Un percorso<br>comprensibile.</h1><p>Il metodo mostrato è uno schema dimostrativo da adattare al processo reale dell’impresa.</p></section><section class="demo-section"><ol class="demo-method"><li><h2>Raccogliere la richiesta</h2><p>Il cliente descrive situazione, contesto e risultato atteso.</p></li><li><h2>Valutare il perimetro</h2><p>Una persona verifica informazioni e necessità di ulteriori accertamenti. Nessun preventivo automatico viene inventato.</p></li><li><h2>Concordare l’attività</h2><p>Scope, tempi e condizioni sono stabiliti prima dell’intervento.</p></li><li><h2>Documentare la chiusura</h2><p>Si condividono gli output realmente previsti e disponibili.</p></li></ol><a class="demo-btn" href="{base}contatti/">Prova il primo passaggio →</a></section>'
  elif route in ['domande','guida']:
   body=f'<section class="demo-page">{prefix}<h1>Prima della richiesta.</h1><p>Informazioni utili a descrivere il bisogno. Questa demo non sostituisce una valutazione tecnica.</p></section><section class="demo-section"><div class="demo-faq"><details><summary>Quali informazioni preparo?</summary><p>Il contesto dello spazio, una descrizione del bisogno e il risultato desiderato. Nel sito reale i dati richiesti saranno quelli necessari al processo dell’impresa.</p></details><details><summary>Il modulo prenota un intervento?</summary><p>No. In questa demo produce solo un riepilogo nel browser. Non trasmette dati e non conferma disponibilità.</p></details><details><summary>Posso ottenere una diagnosi dal sito?</summary><p>No. Il sito aiuta a descrivere la richiesta e non fornisce istruzioni per intervenire sugli impianti.</p></details><details><summary>Dove trovo zone e tempi reali?</summary><p>Devono essere forniti e verificati dall’impresa prima della pubblicazione del progetto personalizzato. La demo non inventa aree coperte o tempi di intervento.</p></details></div><a class="demo-btn" href="{base}contatti/">Prova la richiesta →</a></section>'
  elif route=='documentazione':
   body=f'<section class="demo-page">{prefix}<h1>Una prova deve<br>essere reale.</h1><p>Questa pagina dimostra come organizzare documentazione verificata, senza attribuire abilitazioni o lavori a un’impresa inesistente.</p></section><section class="demo-section"><div class="demo-columns"><article><h2>Ambito</h2><p>Il progetto reale descrive soltanto gli ambiti documentati e pertinenti dell’impresa.</p></article><article><h2>Contesto</h2><p>Ogni lavoro pubblicabile richiede contesto e autorizzazione all’uso dei materiali.</p></article><article><h2>Validità</h2><p>Documenti e riferimenti devono essere aggiornati e controllati dal responsabile.</p></article></div><p class="demo-note">Nessun certificato, recensione o risultato cliente viene simulato come autentico.</p><a class="demo-btn" href="{base}contatti/">Continua alla richiesta →</a></section>'
  elif route in ['impianti','manutenzione']:
   name='Impianti e rifacimenti' if route=='impianti' else 'Manutenzione e valutazione'
   body=f'<section class="demo-page">{prefix}<h1>{name}.</h1><p>Un percorso dedicato aiuta a raccogliere le informazioni pertinenti senza trasformare il sito in una diagnosi automatica.</p></section><section class="demo-section"><h2>Che cosa descrivere</h2><ul><li>Tipo di spazio e situazione attuale.</li><li>Esigenza osservata e obiettivo desiderato.</li><li>Vincoli da discutere con il professionista.</li></ul><p>Disponibilità, ambito tecnico e necessità di sopralluogo sono decisioni dell’impresa reale. Nessuna promessa operativa viene aggiunta al modello.</p><div class="demo-actions"><a class="demo-btn" href="{base}contatti/">Prepara una richiesta di esempio →</a><a href="{base}guida/">Leggi la guida</a></div></section>'
  else:
   body=f'<section class="demo-page">{prefix}<h1>Prova il percorso<br>di richiesta.</h1><p>Simulazione locale. Non inserire dati personali: nessuna richiesta viene inviata, nessun intervento viene prenotato.</p></section><section class="demo-section"><form id="demo-request" novalidate><div class="demo-field"><label for="need">Quale esigenza vuoi descrivere?</label><select id="need" required><option value="">Scegli un esempio</option><option>Impianto o rifacimento</option><option>Manutenzione</option><option>Valutazione da definire</option></select><span class="demo-error" id="need-error"></span></div><div class="demo-field"><label for="space">Tipo di spazio</label><select id="space" required><option value="">Scegli il contesto</option><option>Spazio abitativo di esempio</option><option>Spazio commerciale di esempio</option><option>Altro contesto</option></select><span class="demo-error" id="space-error"></span></div>'
   if tier!='essential':body+='<div class="demo-field"><label for="goal">Obiettivo della richiesta</label><select id="goal" required><option value="">Scegli un obiettivo</option><option>Capire il perimetro di un nuovo progetto</option><option>Descrivere una necessità di manutenzione</option><option>Preparare una valutazione</option></select><span class="demo-error" id="goal-error"></span></div>'
   if tier=='signature':body+='<div class="demo-field"><label for="constraint">Quale vincolo va chiarito?</label><select id="constraint" required><option value="">Scegli un vincolo</option><option>Tempi da concordare</option><option>Accesso allo spazio</option><option>Perimetro ancora incerto</option></select><span class="demo-error" id="constraint-error"></span></div>'
   body+='<button class="demo-btn" type="submit">Genera il riepilogo dimostrativo →</button><div id="demo-result" role="status" tabindex="-1"></div></form></section>'
  footer=f'<footer><strong>MODELLO ELETTRICISTI / {tier.upper()}</strong><p>Demo navigabile Zulian. Contenuti esemplificativi, nessuna impresa reale, nessun dato inviato.</p><div><a href="/modelli/">Torna ai modelli</a><a href="/prezzi/#{tier}">Condizioni del livello</a><a href="/advisor/">Trova la soluzione</a></div></footer>'
  doc=f'<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{names[route]} · Demo elettricisti {tier.title()} · Zulian</title><meta name="robots" content="noindex,follow"><meta name="description" content="Modello navigabile dimostrativo Zulian, senza impresa reale o invio dati."><link rel="stylesheet" href="/assets/demo.css"><script defer src="/assets/demo.js"></script></head><body class="{tier}"><a class="demo-skip" href="#main">Salta al contenuto</a>{head}<main id="main">{body}</main>{footer}</body></html>'
  path=folder/route/'index.html' if route else folder/'index.html';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(doc)
models=[dict(id='electric-'+tier,sector='Servizi tecnici',package=tier,price=price,pages=len(routes),url=f'/demo/elettricisti-{tier}/',title=f'Elettricisti / {concept}',description={'essential':'Un percorso diretto: attività, servizi e richiesta.','business':'Servizi, metodo e FAQ preparano una richiesta più completa.','signature':'Percorsi dedicati, guida e documentazione accompagnano una valutazione più articolata.'}[tier],customizable='Identità, informazioni, servizi, media con diritti e contatti reali.',limits='Nessun backend, diagnosi, certificato o prenotazione reale nella demo.',functions=['Menu e pagine navigabili','Richiesta simulata con validazione']+(['FAQ'] if tier!='essential' else []),version='2026-09-05',status='QA_PENDING') for tier,price,concept,routes in tiers]
(ROOT/'src/models.json').write_text(json.dumps(models,ensure_ascii=False,indent=2))
print('16 pagine demo generate: Essential3 / Business5 / Signature8. QA_PENDING.')
