import html
e=html.escape
def money(n):return '€'+format(n,',').replace(',','.')
def comparison(data):
 ps=data['packages']
 rows=[('Prezzo finale',[money(p['price'])+' · '+data['commercial']['taxTreatment'] for p in ps]),('Pagine funzionali',[p['pages'] for p in ps]),('Lingue totali, inclusa la principale',[str(p['languages']) for p in ps]),('Video brevi integrati, fino a 20 secondi',['Almeno '+str(p['videos']) for p in ps]),('Testo sorgente lavorabile',['Fino a '+format(p['sourceWords'],',').replace(',','.')+' parole' for p in ps]),('Digital Guide',[p['digitalGuide'] for p in ps]),('Materiali mancanti: soglia inclusa',['1 logo tipografico semplice + fino a 5 visual; limiti nel listino']*3),('Progetto adatto',[p['buyer'] for p in ps]),('Personalizzazione e funzioni',[' · '.join(p['features']) for p in ps]),('Scegli se',[p['fit'] for p in ps]),('Richiede valutazione separata',[p['notFit'] for p in ps]),('Revisioni consolidate',[str(p['rounds']) for p in ps]),('Finestra indicativa',[p['days']+' dopo avvio confermato con materiali e accessi completi' for p in ps]),('Correzioni iniziali',[str(data['commercial']['bugFixDays'])+' giorni nel perimetro; diritti inderogabili preservati']*3),('Pagamento',[f"{data['commercial']['depositPercent']}% all’accettazione · {data['commercial']['balancePercent']}% dopo collaudo positivo, prima della pubblicazione"]*3),('Costi esterni',['Dominio, hosting, licenze, API, consumi e altri fornitori separati']*3)]
 return '<section class="comparison"><h2>Confronta il perimetro.</h2><p>Inclusioni misurabili. Pagine legali fuori conteggio; le versioni linguistiche non moltiplicano le pagine funzionali.</p><div class="comparison-scroll" role="region" aria-label="Confronto dei tre livelli, scorribile orizzontalmente" tabindex="0"><table><caption>Essential, Business e Signature: inclusioni, limiti e condizioni</caption><thead><tr><th scope="col">Dimensione</th>'+''.join('<th scope="col">'+p['name']+'</th>' for p in ps)+'</tr></thead><tbody>'+''.join('<tr><th scope="row">'+e(label)+'</th>'+''.join('<td>'+e(v)+'</td>' for v in vals)+'</tr>' for label,vals in rows)+'</tbody></table></div></section>'
def catalog(data,models):
 packages={p['id']:p for p in data['packages']}
 result='<section data-model-catalog><div class="filters"><div class="field"><label for="model-tier">Livello</label><select id="model-tier" data-model-tier><option value="">Tutti i livelli</option>'+''.join('<option value="'+p['id']+'">'+p['name']+'</option>' for p in data['packages'])+'</select></div><div class="field"><label for="model-sector">Settore</label><select id="model-sector" data-model-sector><option value="">Tutti i settori</option>'+''.join('<option>'+e(s)+'</option>' for s in sorted({m['sector'] for m in models}))+'</select></div><button class="btn" data-model-reset>Azzera filtri</button></div><p data-model-count role="status">'+str(len(models))+' modelli</p><p data-model-empty hidden>Nessun modello corrisponde ai filtri. Prova un altro livello.</p><div class="model-catalog">'
 for m in models:
  p=packages[m['package']]
  result+=f'''<article class="model-entry" data-model-entry data-tier="{p['id']}" data-sector="{e(m['sector'])}"><div class="model-entry-heading"><span class="eyebrow">{e(m['sector'])} / {p['name']}</span><h2>{e(m['title'])}</h2><p>{e(m['description'])}</p><strong class="price">{money(p['price'])}</strong><span class="detail">{data['commercial']['taxTreatment']} · {m['pages']} pagine nella demo; {p['pageCount']} nel pacchetto</span></div><div class="model-entry-details"><h3>Cosa puoi provare</h3><ul>{''.join('<li>'+e(f)+'</li>' for f in m['functions'])}</ul><dl><dt>Adatto se</dt><dd>{e(p['fit'])}</dd><dt>Non adatto se</dt><dd>{e(p['notFit'])}</dd><dt>Personalizzazione</dt><dd>{e(m['customizable'])}</dd><dt>Limiti della demo</dt><dd>{e(m['limits'])}</dd><dt>Costi e dipendenze del progetto</dt><dd>Materiali pronti nel perimetro: inserimento e ottimizzazione inclusi. Per materiali mancanti, soglie ed extra nel listino. Dominio, hosting e provider separati; integrazioni da valutare.</dd></dl><p class="detail">Navigazione responsive · Versione {e(m['version'])} · Contenuti esemplificativi. La demo può mostrare meno pagine rispetto al pacchetto contrattuale.</p><div class="actions"><a class="btn primary" href="{m['url']}">Apri il sito completo ↗</a><a class="btn" href="/advisor/?model={m['id']}&package={p['id']}">Parti da questo modello</a><a href="/prezzi/#{p['id']}">Condizioni {p['name']}</a></div></div></article>'''
 return result+'</div></section>'
